### PR TITLE
Build process for Chinese docs

### PR DESCRIPTION
**Pull request by davidkell**
Build process for ZH docs on mkdocs @springzh @cgq0123 @cryptofreedman

View Vercel app for example of how this looks.

I've gone for a simple solution of running a separate mkdocs project in a sub-directory, and re-using configuration from the parent project. Inspired by [this discussion](https://github.com/squidfunk/mkdocs-material/discussions/2346). As usual, simple solution is the best 😄 

You can just go into the `zh` directory and run `mkdocs serve`. It's totally separate. You can override anything e.g. site name, or if you want to setup [Chinese language support](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#chinese-language-support) for the search.

If you are happy we can merge into your branch. Thank you!

### CODE REVIEW

**Comment by davidkell** [comment]
Makes sense @springzh

Feel free to close this PR, or keep it open as a reference as you wish

Note that to deploy the ZH docs on Vercel, I will need to update the build process. So just tag me in the PR when you merge into`master`.

**Comment by cgq0123** [comment]
Spring has reworked this and integrated the changes in: https://github.com/duneanalytics/docs/pull/183, this PR could be closed upon review

**Comment by cryptofreedman** [comment]
Ty!

**Comment by davidkell** [comment]
Closed in favour of #208

**Pull request closed without merging**
